name: fair_graph310_fmmc
channels:
  - conda-forge
dependencies:
  - python=3.10
  - brewer2mpl=1.4.1
  - cairocffi=1.4.0
  - cffi=1.15.1
  - contourpy=1.0.6
  - cycler=0.11.0
  - fonttools=4.38.0
  - gensim=4.2.0
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - matplotlib=3.6.2
  - networkx=2.8.8
  - numpy=1.23.5
  - packaging=21.3
  - pandas=1.5.1
  - patsy=0.5.3
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.1
  - setuptools=57.4.0
  - six=1.16.0
  - smart-open=6.2.0
  - statsmodels=0.13.5
  - texttable=1.6.5
  - threadpoolctl=3.1.0
  - tqdm=4.64.1
  - pycparser=2.21
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pytz=2022.6
  - cvxpy=1.5.2
  - cvxopt  # Installed via conda-forge to ensure compatibility
  - scs     # Installed via conda-forge to ensure compatibility
  - clarabel  # If available via conda-forge
  - pip
  - pip:
      - pillow==9.3.0  # Install Pillow via pip
      # - mosek # be aware of the necessary
      - igraph==0.10.2
